branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/
language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
script: python tests.py
after_success: python2.7 deploy_addon.py -r -d
before_deploy:
 - export RELEASE_ZIP=$(ls *.zip)
 - echo deploying $RELEASE_ZIP to GitHub releases
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: $RELEASE_ZIP
  skip_cleanup: true
  on:
    tags: true
